### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by echopage** [madmicio/ph-meter-temperature#3]
Non è un errore di programmazione: nelle ultime righe hai scritto temperatura quando doveva essere scritto ph:
acquario_ph_high:
  name: allarme temperatura elevata
  initial: 7.9
  min: 7
  max: 8
  step: 0.01
acquario_ph_low:
  name: allarme temperatura bassa
  initial: 6.8
  min: 6
  max: 7
  step: 0.01

PS
cosa usi come sensore ph compatibile con home assistant?

**Comment by madmicio** [comment]
grazie
